name: CI

on: [push]

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare environment - check out the repository
        uses: actions/checkout@v6
      - name: Prepare environment - install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Increment patch version
        run: mvn --batch-mode release:update-versions -f hello/pom.xml
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Increment patch version" || exit 0
          git push

